<?php

namespace Database\Seeders;

use App\Models\MatchTickerTemplate;
use Illuminate\Database\Seeder;

class MatchTickerTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            'goal' => [
                'TOOOOR! {player} fackelt nicht lange und jagt das Leder in die Maschen!',
                'Was für ein Treffer! {player} lässt dem Keeper keine Chance.',
                'Tor für {club}! {player} steht goldrichtig und staubt ab.',
                'Gänsehaut pur! {player} mit einem Traumtor aus der Distanz!',
                'Da ist das Ding! {player} markiert das {score}.',
                'Eiskalt! {player} verwandelt sicher zur Führung für {club}.',
                'Unglaublich! {player} schlenzt den Ball unhaltbar in den Winkel.',
                'Tor, Tor, Tor! {player} krönt seine starke Leistung mit diesem Treffer.',
                'Der Bann ist gebrochen! {player} trifft zum {score}.',
                'Präzision pur! {player} setzt den Ball flach ins linke Eck.',
                'Kopfball-Ungeheuer! {player} schraubt sich hoch und nickt ein.',
                'Blitzsauberer Konter! {player} schließt eiskalt zum {score} ab.',
                'Ein Hammer! {player} zieht aus 20 Metern ab – drin!',
                'Jubel bei {club}! {player} lässt die Abwehr alt aussehen.',
                'Spielfreude pur: {player} tanzt zwei Gegner aus und versenkt.',
                'Das Stadion bebt! {player} trifft für {club}.',
                'Abstauber-König! {player} steht genau da, wo ein Stürmer stehen muss.',
                'Wunderschön herausgespielt! {player} muss nur noch den Fuß hinhalten.',
                'Direktabnahme! {player} trifft den Ball perfekt – keine Abwehrchance.',
                'Tor! {player} behält im Gewusel die Übersicht und netzt ein.',
                'Einfach nur Weltklasse! {player} trifft zum {score}.',
                'Der Keeper ist geschlagen! {player} netzt trocken ein.',
                'Was für eine Fackel! {player} lässt das Netz zappeln.',
                'Instinktfußballer! {player} riecht den Braten und trifft.',
                'Tooor! Ein Strahl von {player} landet genau im Knick.',
                'Marke Tor des Monats! {player} lässt alle staunen.',
                'Der Druck war zu groß: {player} vollendet für {club}.',
                'Sicher verwandelt! {player} macht das {score}.',
                'Ein genialer Moment von {player} führt zum Tor!',
                'Die Fans flippen aus! {player} trifft zum {score}.',
                'Da hat die Abwehr gepennt! {player} sagt Danke und schiebt ein.',
                'Technisch perfekt! {player} legt den Ball am Torwart vorbei.',
                'Toooor! {player} trifft per Direktabnahme nach einer Ecke.',
                'Sensationell! {player} mit dem Solo und dem Abschluss.',
                'Was für ein Pfund! {player} hämmert den Ball ins Tor.',
                'Kaltblütig! {player} lässt sich diese Chance nicht nehmen.',
                'Tor! {player} belohnt den Sturmlauf von {club}.',
                'Ein Gedicht von einem Tor! {player} trifft zum {score}.',
                'Der Ball schlägt ein! {player} ist der Torschütze.',
                'Toooor! {player} bringt das Stadion zum Kochen.',
            ],
            'chance' => [
                'Fast das Tor! {player} verfehlt das Gehäuse nur um Zentimeter.',
                'Riesen-Möglichkeit für {club}! {player} scheitert am Pfosten.',
                'Was für eine Parade! Der Keeper fischt den Schuss von {player} aus dem Eck.',
                '{player} zieht ab, aber der Ball segelt knapp über die Querlatte.',
                'Fast der Jubel! {player} probiert es mit einem Heber, aber der Verteidiger klärt auf der Linie.',
                'Glanztat! {player} kommt frei zum Abschluss, aber der Torwart ist blitzschnell unten.',
                'Das hätte es sein müssen! {player} setzt den Ball völlig frei am Tor vorbei.',
                'Dicke Chance für {player}! Doch sein Schuss wird im letzten Moment geblockt.',
                'Alutreffer! {player} hämmert das Leder gegen das Lattenkreuz.',
                'Knapp vorbei! {player} zielt auf das lange Eck, aber der Ball streicht am Pfosten vorbei.',
                '{player} hat das Auge für die Lücke, aber sein Abschluss ist zu ungenau.',
                'Wahnsinn! {player} macht eigentlich alles richtig, trifft aber nur das Außennetz.',
                'Gefährlich! {player} mit einem strammen Schuss, der Keeper kann nur zur Seite abwehren.',
                '{club} drückt! {player} kommt zum Kopfball, aber der Ball geht drüber.',
                'Hundertprozentige! {player} läuft allein auf den Torwart zu, zögert aber zu lange.',
                'Szenenapplaus! {player} mit einem Fallrückzieher, aber knapp vorbei.',
                'Der Keeper rettet mit den Fingerspitzen gegen {player}!',
                '{player} tanzt seinen Gegenspieler aus, verzieht dann aber völlig.',
                'Fast der Ausgleich! {player} setzt einen Freistoß an die Latte.',
                'Chaos im Strafraum! {player} stochert nach, aber der Ball will nicht rein.',
                'Starker Reflex! {player} köpft aus fünf Metern, aber der Torwart hält.',
                'Das war knapp! {player} mit einem Distanzschuss, der leicht abgefälscht wird.',
                'Riesenglück für {club}! {player} trifft nur das Aluminium.',
                '{player} setzt nach, doch der Ball bleibt in der Abwehr hängen.',
                'Brandgefährlich! {player} schlenzt den Ball um die Mauer, aber knapp vorbei.',
                'Der Atem stockt! {player} verpasst die Hereingabe nur um Haaresbreite.',
                'Riesen-Save! {player} kann es selbst kaum glauben.',
                'Fast ein Eigentor! {player} provoziert die Unordnung im Strafraum.',
                'Da fehlte nicht viel! {player} probiert es mit Gewalt.',
                'Abschluss von {player}, aber der Winkel war zu spitz.',
                'Großchance! {player} bekommt den Ball ideal serviert, zielt aber drüber.',
                'Packendes Duell! {player} versucht es flach, doch Endstation ist beim Keeper.',
                'Die Fans hatten den Torschrei schon auf den Lippen! {player} vergibt.',
                'Fast der entscheidende Moment durch {player}!',
                'Druckphase von {club}! {player} prüft den Torwart erneut.',
                'Da war mehr drin! {player} entscheidet sich für die falsche Ecke.',
                'Heißes Ding! {player} mit dem Volley, aber genau auf den Mann.',
                'Zentimeterarbeit! {player} schrammt am Führungstreffer vorbei.',
                'Kein Glück für {player}! Der Ball springt vom Pfosten zurück ins Feld.',
                'Toller Versuch von {player}, aber letztlich harmlos.',
            ],
            'yellow_card' => [
                'Gelb für {player} nach einem taktischen Foul.',
                'Der Schiedsrichter zeigt {player} die Gelbe Karte. Zu hart eingestiegen.',
                'Verwarnung für {player}. Er hatte nur die Beine des Gegners im Visier.',
                'Gelbe Karte! {player} unterbindet den Konter mit unfairen Mitteln.',
                'Das hat Folgen: Gelb für {player} nach mehrmaligem Foulspiel.',
                'Gelb wegen Meckerns! {player} sollte sich besser auf das Spiel konzentrieren.',
                'Zu spät gekommen! {player} sieht völlig zurecht Gelb.',
                'Dunkelgelb! {player} kommt mit einer Verwarnung davon.',
                'Gelb für {player}. Das war ein klares Frustfoul.',
                'Der Schiri zückt Gelb für {player} wegen Ballwegschlagens.',
                '{player} sieht Gelb. Er hat den Gegenspieler am Trikot festgehalten.',
                'Gelbe Karte für {player} nach einem absichtlichen Handspiel.',
                'Eindeutig: Gelb für {player} wegen gefährlichen Spiels.',
                '{player} wird verwarnt. Das nächste Mal fliegt er vom Platz.',
                'Gelbe Karte! {player} hat sich zu lautstark beschwert.',
                'Gelb für {player}. Ein Foul mit Ansage.',
                'Der Referee kennt kein Pardon: Gelb für {player}.',
                'Gelbe Karte für {player} - er hat den Sturmlauf unsanft gestoppt.',
                '{player} ist jetzt vorbelastet. Gelb nach diesem Einsatz.',
                'Klares Signal: Gelb für {player} nach einem rüden Einsteigen.',
            ],
            'red_card' => [
                'PLATZVERWEIS! {player} sieht nach diesem brutalen Foul glatt Rot!',
                'Rote Karte für {player}! {club} muss nun in Unterzahl weiterspielen.',
                'Notbremse! Der Schiedsrichter schickt {player} vorzeitig unter die Dusche.',
                'Unfassbar! {player} lässt sich zu einer Tätlichkeit hinreißen. Rot!',
                'Glatt Rot für {player}! Das war völlig unnötig.',
                'Der Schiedsrichter zeigt {player} die Rote Karte nach einem groben Foul.',
                'Ampelkarte! Nachdem {player} bereits Gelb hatte, sieht er nun Gelb-Rot.',
                '{player} muss den Platz verlassen! Gelb-Rot nach erneutem Foulspiel.',
                'Aus und vorbei! {player} sieht Rot und fehlt im nächsten Spiel.',
                'Platzverweis gegen {player}. Eine harte, aber vertretbare Entscheidung.',
            ],
            'foul' => [
                'Pfiff des Unparteiischen: Foul von {player}.',
                'Harter Einsatz von {player} gegen {opponent}. Freistoß!',
                '{player} rempelt {opponent} unsanft um. Der Schiri mahnt ihn an.',
                'Kleines Foulspiel von {player} im Mittelfeld.',
                '{player} zieht am Trikot von {opponent}. Das Spiel wird unterbrochen.',
                '{player} bringt {opponent} zu Fall. Klare Sache: Freistoß.',
                'Nickligkeiten im Mittelfeld: {player} begeht ein kleines Foul.',
                'Stoppfehler mit Folgen: {player} muss zum Foul greifen.',
                '{player} trifft nur den Mann, nicht den Ball. Foul an {opponent}.',
                'Aggressives Pressing von {player}, das in einem Foul endet.',
                'Freistoß für die Gegenseite nach einem Foul von {player}.',
                '{player} steigt {opponent} auf den Fuß. Schmerzhaft!',
                'Der Schiedsrichter unterbricht die Partie. Foul von {player}.',
                '{player} lässt das Bein stehen. Foul an {opponent}.',
                '{opponent} wird von {player} unsanft gestoppt.',
                'Taktisches Zupfen von {player}. Der Schiedsrichter pfeift.',
                'Hektik auf dem Platz: {player} begeht das nächste Foul.',
                'Körperbetontes Spiel von {player}, doch das war zu viel.',
                'Foulspiel von {player} an der Seitenauslinie.',
                '{player} schiebt gegen {opponent}. Der Schiedsrichter hat es gesehen.',
            ],
            'substitution' => [
                'Wechsel bei {club}: {player} kommt für frischen Wind ins Spiel.',
                'Taktischer Wechsel: {player} betritt das Feld.',
                'Dienstschluss für heute. {player} übernimmt jetzt die Position.',
                'Applaus der Fans: {player} kommt neu in die Partie.',
                '{club} wechselt: {player} ist jetzt dabei.',
                'Frische Kräfte für {club}: {player} greift jetzt ein.',
                'Der Trainer reagiert: {player} wird eingewechselt.',
                'Wechselzeit! {player} soll für neue Akzente sorgen.',
                '{player} verstärkt jetzt die Defensive von {club}.',
                'Offensiv-Wechsel: {player} stürmt jetzt für {club}.',
                'Ein neuer Mann auf dem Platz: {player} ist jetzt im Spiel.',
                'Wechsel bei {club}: {player} ist bereit für seinen Einsatz.',
                'Kurze Pause für Anweisungen, dann kommt {player} aufs Feld.',
                '{player} ersetzt seinen erschöpften Mitspieler.',
                'Hoffnungsträger? {player} wird eingewechselt.',
                'Ein vertrautes Gesicht: {player} kommt für {club} in die Partie.',
                'Wechsel bei {club}: Mal sehen, was {player} bewirken kann.',
                'Letzter Wechsel wahrscheinlich: {player} kommt rein.',
                'Verstärkung für das Mittelfeld: {player} betritt den Rasen.',
                'Stabwechsel bei {club}: {player} übernimmt.',
            ],
            'injury' => [
                'Sorgenfalten bei {club}: {player} hält sich das Knie und muss behandelt werden.',
                '{player} liegt am Boden. Das sieht nach einer Muskelverletzung aus.',
                'Kurze Unterbrechung: {player} scheint sich ohne gegnerische Einwirkung verletzt zu haben.',
                'Oje, {player} signalisiert sofort: Es geht nicht weiter.',
                'Verletzungspech für {player}. Er muss vom Platz getragen werden.',
                'Harter Zusammenprall! {player} muss am Kopf behandelt werden.',
                'Der Physiotherapeut eilt auf das Feld zu {player}.',
                'Bitter für {club}: {player} kann wohl nicht weitermachen.',
                '{player} hinkt vom Platz. Wir hoffen auf nichts Ernstes.',
                'Unsportlich? Nein, {player} ist wirklich schmerzverzerrt am Boden.',
            ]
        ];

        foreach ($templates as $type => $texts) {
            foreach ($texts as $text) {
                MatchTickerTemplate::create([
                    'event_type' => $type,
                    'text' => $text,
                    'priority' => 'normal',
                    'locale' => 'de',
                ]);
            }
        }
    }
}
