<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    /**
     * Expand the event_type ENUM to include all event types generated by
     * MatchSimulationService (generic events) and ActionEngine (live sim).
     */
    public function up(): void
    {
        DB::statement("ALTER TABLE match_events MODIFY COLUMN event_type ENUM(
            'goal',
            'own_goal',
            'yellow_card',
            'red_card',
            'substitution',
            'injury',
            'penalty_scored',
            'penalty_missed',
            'save',
            'chance',
            'foul',
            'corner',
            'free_kick',
            'offside',
            'shot',
            'clearance',
            'throw_in',
            'turnover',
            'midfield_possession',
            'kickoff',
            'half_time',
            'full_time'
        ) NOT NULL");
    }

    /**
     * Revert to original ENUM values.
     */
    public function down(): void
    {
        DB::statement("ALTER TABLE match_events MODIFY COLUMN event_type ENUM(
            'goal',
            'own_goal',
            'yellow_card',
            'red_card',
            'substitution',
            'injury',
            'penalty_scored',
            'penalty_missed',
            'save',
            'chance'
        ) NOT NULL");
    }
};
