<?php

return [
    'default' => '4-4-2',

    'layouts' => [
        '4-4-2' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 52],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 52],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 52],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 52],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 32],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 32],
        ],
        '4-4-2 (Holding)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM-L', 'label' => 'DM', 'group' => 'MID', 'x' => 40, 'y' => 58],
            ['slot' => 'DM-R', 'label' => 'DM', 'group' => 'MID', 'x' => 60, 'y' => 58],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 45],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 45],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '4-3-3' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 32, 'y' => 54],
            ['slot' => 'ZM', 'label' => 'ZM', 'group' => 'MID', 'x' => 50, 'y' => 54],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 68, 'y' => 54],
            ['slot' => 'LF', 'label' => 'LF', 'group' => 'FWD', 'x' => 22, 'y' => 34],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
            ['slot' => 'RF', 'label' => 'RF', 'group' => 'FWD', 'x' => 78, 'y' => 34],
        ],
        '4-3-3 (Attack)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 58],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 58],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 44],
            ['slot' => 'LF', 'label' => 'LF', 'group' => 'FWD', 'x' => 22, 'y' => 34],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
            ['slot' => 'RF', 'label' => 'RF', 'group' => 'FWD', 'x' => 78, 'y' => 34],
        ],
        '4-3-3 (Defend)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM-L', 'label' => 'DM', 'group' => 'MID', 'x' => 35, 'y' => 60],
            ['slot' => 'DM-R', 'label' => 'DM', 'group' => 'MID', 'x' => 65, 'y' => 60],
            ['slot' => 'ZM', 'label' => 'ZM', 'group' => 'MID', 'x' => 50, 'y' => 50],
            ['slot' => 'LF', 'label' => 'LF', 'group' => 'FWD', 'x' => 22, 'y' => 34],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
            ['slot' => 'RF', 'label' => 'RF', 'group' => 'FWD', 'x' => 78, 'y' => 34],
        ],
        '4-3-3 (Holding)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM', 'label' => 'DM', 'group' => 'MID', 'x' => 50, 'y' => 62],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 35, 'y' => 50],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 65, 'y' => 50],
            ['slot' => 'LF', 'label' => 'LF', 'group' => 'FWD', 'x' => 22, 'y' => 34],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
            ['slot' => 'RF', 'label' => 'RF', 'group' => 'FWD', 'x' => 78, 'y' => 34],
        ],
        '4-3-3 (False 9)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM', 'label' => 'DM', 'group' => 'MID', 'x' => 50, 'y' => 62],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 35, 'y' => 50],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 65, 'y' => 50],
            ['slot' => 'LF', 'label' => 'LF', 'group' => 'FWD', 'x' => 22, 'y' => 34],
            ['slot' => 'MS', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 36],
            ['slot' => 'RF', 'label' => 'RF', 'group' => 'FWD', 'x' => 78, 'y' => 34],
        ],
        '4-2-3-1 (Wide)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM-L', 'label' => 'DM', 'group' => 'MID', 'x' => 40, 'y' => 60],
            ['slot' => 'DM-R', 'label' => 'DM', 'group' => 'MID', 'x' => 60, 'y' => 60],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 45],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 42],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 45],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
        ],
        '4-2-3-1 (Narrow)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM-L', 'label' => 'DM', 'group' => 'MID', 'x' => 40, 'y' => 60],
            ['slot' => 'DM-R', 'label' => 'DM', 'group' => 'MID', 'x' => 60, 'y' => 60],
            ['slot' => 'LAM', 'label' => 'LAM', 'group' => 'MID', 'x' => 35, 'y' => 44],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 42],
            ['slot' => 'RAM', 'label' => 'RAM', 'group' => 'MID', 'x' => 65, 'y' => 44],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
        ],
        '4-1-2-1-2 (Wide)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM', 'label' => 'DM', 'group' => 'MID', 'x' => 50, 'y' => 62],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 48],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 48],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 42],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '4-1-2-1-2 (Narrow)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM', 'label' => 'DM', 'group' => 'MID', 'x' => 50, 'y' => 62],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 52],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 52],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 42],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '4-2-2-2' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM-L', 'label' => 'DM', 'group' => 'MID', 'x' => 40, 'y' => 60],
            ['slot' => 'DM-R', 'label' => 'DM', 'group' => 'MID', 'x' => 60, 'y' => 60],
            ['slot' => 'ZOM-L', 'label' => 'ZOM', 'group' => 'MID', 'x' => 35, 'y' => 44],
            ['slot' => 'ZOM-R', 'label' => 'ZOM', 'group' => 'MID', 'x' => 65, 'y' => 44],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '4-3-2-1' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 32, 'y' => 54],
            ['slot' => 'ZM', 'label' => 'ZM', 'group' => 'MID', 'x' => 50, 'y' => 54],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 68, 'y' => 54],
            ['slot' => 'LS', 'label' => 'LS', 'group' => 'FWD', 'x' => 35, 'y' => 38],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
            ['slot' => 'RS', 'label' => 'RS', 'group' => 'FWD', 'x' => 65, 'y' => 38],
        ],
        '4-3-1-2' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 32, 'y' => 54],
            ['slot' => 'ZM', 'label' => 'ZM', 'group' => 'MID', 'x' => 50, 'y' => 54],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 68, 'y' => 54],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 42],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '4-4-1-1 (Midfield)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 52],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 52],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 52],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 52],
            ['slot' => 'MS', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 38],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 24],
        ],
        '4-1-4-1' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LV', 'label' => 'LV', 'group' => 'DEF', 'x' => 15, 'y' => 72],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 38, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 62, 'y' => 72],
            ['slot' => 'RV', 'label' => 'RV', 'group' => 'DEF', 'x' => 85, 'y' => 72],
            ['slot' => 'DM', 'label' => 'DM', 'group' => 'MID', 'x' => 50, 'y' => 62],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 48],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 48],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 48],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 48],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
        ],
        '3-4-1-2' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 52],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 54],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 54],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 52],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 42],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '3-4-2-1' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 52],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 54],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 54],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 52],
            ['slot' => 'LS', 'label' => 'LS', 'group' => 'FWD', 'x' => 38, 'y' => 38],
            ['slot' => 'RS', 'label' => 'RS', 'group' => 'FWD', 'x' => 62, 'y' => 38],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 26],
        ],
        '3-4-3 (Flat)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 52],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 52],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 52],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 52],
            ['slot' => 'LF', 'label' => 'LF', 'group' => 'FWD', 'x' => 22, 'y' => 32],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 28],
            ['slot' => 'RF', 'label' => 'RF', 'group' => 'FWD', 'x' => 78, 'y' => 32],
        ],
        '3-4-3 (Diamond)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'DM', 'label' => 'DM', 'group' => 'MID', 'x' => 50, 'y' => 60],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 18, 'y' => 48],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 82, 'y' => 48],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 42],
            ['slot' => 'LF', 'label' => 'LF', 'group' => 'FWD', 'x' => 24, 'y' => 30],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 26],
            ['slot' => 'RF', 'label' => 'RF', 'group' => 'FWD', 'x' => 76, 'y' => 30],
        ],
        '3-1-4-2' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'DM', 'label' => 'DM', 'group' => 'MID', 'x' => 50, 'y' => 62],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 14, 'y' => 48],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 48],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 48],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 86, 'y' => 48],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '3-5-2' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 12, 'y' => 52],
            ['slot' => 'DM-L', 'label' => 'DM', 'group' => 'MID', 'x' => 35, 'y' => 58],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 42],
            ['slot' => 'DM-R', 'label' => 'DM', 'group' => 'MID', 'x' => 65, 'y' => 58],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 88, 'y' => 52],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '3-5-1-1' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 12, 'y' => 52],
            ['slot' => 'DM-L', 'label' => 'DM', 'group' => 'MID', 'x' => 35, 'y' => 58],
            ['slot' => 'ZM', 'label' => 'ZM', 'group' => 'MID', 'x' => 50, 'y' => 54],
            ['slot' => 'DM-R', 'label' => 'DM', 'group' => 'MID', 'x' => 65, 'y' => 58],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 88, 'y' => 52],
            ['slot' => 'MS', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 38],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 24],
        ],
        '5-2-1-2' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LWB', 'label' => 'LWB', 'group' => 'DEF', 'x' => 10, 'y' => 68],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'RWB', 'label' => 'RWB', 'group' => 'DEF', 'x' => 90, 'y' => 68],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 54],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 54],
            ['slot' => 'ZOM', 'label' => 'ZOM', 'group' => 'MID', 'x' => 50, 'y' => 44],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 28],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 28],
        ],
        '5-2-2-1' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LWB', 'label' => 'LWB', 'group' => 'DEF', 'x' => 10, 'y' => 68],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'RWB', 'label' => 'RWB', 'group' => 'DEF', 'x' => 90, 'y' => 68],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 38, 'y' => 54],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 62, 'y' => 54],
            ['slot' => 'LS', 'label' => 'LS', 'group' => 'FWD', 'x' => 38, 'y' => 38],
            ['slot' => 'RS', 'label' => 'RS', 'group' => 'FWD', 'x' => 62, 'y' => 38],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 24],
        ],
        '5-3-2' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LWB', 'label' => 'LWB', 'group' => 'DEF', 'x' => 10, 'y' => 68],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'RWB', 'label' => 'RWB', 'group' => 'DEF', 'x' => 90, 'y' => 68],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 32, 'y' => 54],
            ['slot' => 'ZM', 'label' => 'ZM', 'group' => 'MID', 'x' => 50, 'y' => 54],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 68, 'y' => 54],
            ['slot' => 'ST-L', 'label' => 'MS', 'group' => 'FWD', 'x' => 43, 'y' => 30],
            ['slot' => 'ST-R', 'label' => 'MS', 'group' => 'FWD', 'x' => 57, 'y' => 30],
        ],
        '5-4-1 (Flat)' => [
            ['slot' => 'TW', 'label' => 'TW', 'group' => 'GK', 'x' => 50, 'y' => 88],
            ['slot' => 'LWB', 'label' => 'LWB', 'group' => 'DEF', 'x' => 10, 'y' => 68],
            ['slot' => 'IV-L', 'label' => 'IV', 'group' => 'DEF', 'x' => 30, 'y' => 74],
            ['slot' => 'IV', 'label' => 'IV', 'group' => 'DEF', 'x' => 50, 'y' => 72],
            ['slot' => 'IV-R', 'label' => 'IV', 'group' => 'DEF', 'x' => 70, 'y' => 74],
            ['slot' => 'RWB', 'label' => 'RWB', 'group' => 'DEF', 'x' => 90, 'y' => 68],
            ['slot' => 'LM', 'label' => 'LM', 'group' => 'MID', 'x' => 18, 'y' => 48],
            ['slot' => 'ZM-L', 'label' => 'ZM', 'group' => 'MID', 'x' => 40, 'y' => 52],
            ['slot' => 'ZM-R', 'label' => 'ZM', 'group' => 'MID', 'x' => 60, 'y' => 52],
            ['slot' => 'RM', 'label' => 'RM', 'group' => 'MID', 'x' => 82, 'y' => 48],
            ['slot' => 'ST', 'label' => 'MS', 'group' => 'FWD', 'x' => 50, 'y' => 26],
        ],
    ],
];
